<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{45608e08-666f-403e-a083-2e21d622d99c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	RunnerTests : RunnerTestSuite;
	ObjectTests : ObjectTestSuite;
	TraceTests : TraceTestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RunnerTests();
ObjectTests();
TraceTests();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>