<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CyclicBase" Id="{822a4270-a76d-44ce-8055-ee2099020175}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT CyclicBase IMPLEMENTS I_Cyclic
VAR
	iLogger : I_Message;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[{analysis -2}]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{9762b721-7f92-40df-8e44-4acdbac204f1}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT Cycle : HRESULT
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{analysis -2}]]></ST>
      </Implementation>
    </Method>
    <Property Name="Logger" Id="{99e0c556-11d4-44e4-8dcc-e93ffcb49823}">
      <Declaration><![CDATA[PROPERTY Logger : I_Message]]></Declaration>
      <Set Name="Set" Id="{ef61a08c-5eed-453b-8a04-5ea1b1ea1393}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[iLogger := Logger;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>